### ISSUE TITLE
Please tag for downstream projects

### ISSUE THREAD

**Issue by inglor** [containers/shortnames#39]
Consider tagging for release so this can be packaged properly. This would help downstream distros.

**Comment by vrothberg** [comment]
Thanks for reaching out!

No objections from my side. I wonder which versioning scheme should be used. A systemd-like simple integer seems the most applicable option to me.

@rhatdan @fatherlinux WDYT?

**Comment by dvzrv** [comment]
> No objections from my side. I wonder which versioning scheme should be used. A systemd-like simple integer seems the most applicable option to me.

Either that or [calver](https://calver.org) might also work :)

**Comment by rhatdan** [comment]
Went with the calendar release. Simple and conveys some information.
https://github.com/containers/shortnames/releases/tag/v2022.02.08
