### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by dcermak** [containers/shortnames#49]
I haven't found a license attached to this project, which could be problematic for redistribution. Could we add one?

I am not a lawyer, thus I am not sure if `shortnames.conf` qualifies as copyrightable, but my approach would have been better safe than sorry.

**Comment by rhatdan** [comment]
@vrothberg @dcermak suggestion on a license?  Since there is no code, would this just be copyright?

**Comment by vrothberg** [comment]
I'm not a lawyer but using Apache v2 seems safe as all other projects use it.

**Comment by rhatdan** [comment]
SGTM, could you open a PR?
