### ISSUE TITLE
Need official images from CENTOS

### ISSUE THREAD

**Issue by rhatdan** [containers/shortnames#5]

**Comment by vrothberg** [comment]
@lsm5 @jnovy do you know who maintains the images? I searched the web and looked for a maintainer in the image configs but could not find one yet.

**Comment by jnovy** [comment]
@vrothberg I only see Brian Stinson doing something with CentOS images here: https://github.com/CentOS/sig-cloud-instance-images/blob/12a4f1c0d78e257ce3d33fe89092eee07e6574da/docker/Dockerfile

**Comment by lsm5** [comment]
@bstinsonmhk PTAL
