### ISSUE TITLE
Do not reserve unrelated short names

### ISSUE THREAD

**Issue by vrothberg** [containers/shortnames#7]
At the time of writing, the list includes aliases for short names that the respective projects should decide and not the distribution.

For instance:
```
"inkscape" = "registry.fedoraproject.org/inkscape"
```

Inkscape does not belong to Fedora and as such it should not auto-resolve to the Fedora registry. Only Fedora images should resolve to it.

@rhatdan PTAL

**Comment by rhatdan** [comment]
Open a PR to remove it.

**Comment by vrothberg** [comment]
I don't have time at the moment but wanted to raise awareness early on.

**Comment by rhatdan** [comment]
They have been removed.
